[package]
name = "prefixopt"
version = "0.1.0"
authors = ["Ruben Lapauw <Ruben.Lapauw@cs.kuleuven.be>"]

[dependencies]
#clap = {version= "2.23.1", features=["debug"]}
clap = "2.23.1"
map_in_place = "0.1.0"
