[package]
name = "prefixopt"
version = "0.1.0"
authors = ["Ruben Lapauw <Ruben.Lapauw@cs.kuleuven.be>"]
license = "MIT/Apache-2.0"

[dependencies]
#clap = {version= "2.23.1", features=["debug"]}
clap = "^2.23"
map_in_place = "0.1.0"

[lib]
