[package]
name = "prefixopt_derive"
version = "0.1.0"
authors = ["Ruben Lapauw <Ruben.Lapauw@cs.kuleuven.be>"]

[dependencies]
syn = "0.11.4"
quote = "0.3.12"
prefixopt = { path = "../prefixopt" }

[lib]
proc-macro = true
